name: ci-cd-deploy-app-to-eks

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ECR Container Registry
        uses: docker/login-action@v1
        with:
          registry: 864185773574.dkr.ecr.ap-northeast-1.amazonaws.com
          username: AWS
          password: ${{ secrets.AWS_SECRET_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            864185773574.dkr.ecr.ap-northeast-1.amazonaws.com/flask_app:latest

      -
        name: Push to k8s
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.AWS_EKS_CONFIG }}
          command: apply -f ./k8s/deployment.yaml
      -
        name: Rollout K8s deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.AWS_EKS_CONFIG }}
          command: rollout restart deployment flask
