name: Terraform CI

on:
  push:
    branches:
    - testing

jobs:
  apply:
    name: terraform apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.9
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './terraform'
          tf_actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SECRET_PRIVATE_KEY: ${{ secrets.AWS_SECRET_PRIVATE_KEY }}
          environment: dev
      - name: terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.9
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './terraform'
          tf_actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SECRET_PRIVATE_KEY: ${{ secrets.AWS_SECRET_PRIVATE_KEY }}
          environment: dev