name: Terraform CI

on:
  workflow_dispatch:
jobs:
  run-terraform:
    name: Run terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.9
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './terraform'
          tf_actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_PRIVATE_KEY: ${{ secrets.AWS_SECRET_PRIVATE_KEY }}
          TF_VAR_environment: "dev"
      - name: terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.9
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './terraform'
          tf_actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_PRIVATE_KEY: ${{ secrets.AWS_SECRET_PRIVATE_KEY }}
          TF_VAR_environment: "dev"
      - name: terraform apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.9
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './terraform'
          tf_actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_PRIVATE_KEY: ${{ secrets.AWS_SECRET_PRIVATE_KEY }}
          TF_VAR_environment: "dev"
      - name: terraform destroy
        if: ${{ failure() }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.9
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: './terraform'
          tf_actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_PRIVATE_KEY: ${{ secrets.AWS_SECRET_PRIVATE_KEY }}
          TF_VAR_environment: "dev"
