name: Terraform CI

on:
  push:
    branches:
    - testing

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run a Terraform init
        uses: docker://hashicorp/terraform:1.0.9
        with:
          entrypoint: terraform
          args: -chdir=./terraform init

      - name: Run a Terraform validate
        uses: docker://hashicorp/terraform:1.0.9
        with:
          entrypoint: terraform
          args: -chdir=./terraform validate
